
/* Facts */

travel_dist(agartala,ahmedabad,3305).              travel_dist(ahmedabad,agartala,3305).
travel_dist(agartala,bangalore,3824).              travel_dist(bangalore,agartala,3824).
travel_dist(agartala,bhubaneshwar,2286).           travel_dist(bhubaneshwar,agartala,2286).
travel_dist(agartala,bombay,3593).                 travel_dist(bombay,agartala,3593).
travel_dist(agartala,calcutta,1863).               travel_dist(calcutta,agartala,1863).
travel_dist(agartala,chandigarh,2998).             travel_dist(chandigarh,agartala,2998).
travel_dist(agartala,cochin,4304).                 travel_dist(cochin,agartala,4304).
travel_dist(agartala,delhi,2708).                  travel_dist(delhi,agartala,2708).
travel_dist(agartala,hyderabad,3330).              travel_dist(hyderabad,agartala,3330).
travel_dist(agartala,indore,2891).                 travel_dist(indore,agartala,2891).
travel_dist(agartala,jaipur,2801).                 travel_dist(jaipur,agartala,2801).
travel_dist(agartala,kanpur,2281).                 travel_dist(kanpur,agartala,2281).
travel_dist(agartala,lucknow,2252).                travel_dist(lucknow,agartala,2252).
travel_dist(agartala,madras,3493).                 travel_dist(madras,agartala,3493).
travel_dist(agartala,nagpur,2696).                 travel_dist(nagpur,agartala,2696).
travel_dist(agartala,nasik,3365).                  travel_dist(nasik,agartala,3365).
travel_dist(agartala,panjim,3507).                 travel_dist(panjim,agartala,3507).
travel_dist(agartala,patna,1681).                  travel_dist(patna,agartala,1681).
travel_dist(agartala,pondicherry,3661).            travel_dist(pondicherry,agartala,3661).
travel_dist(agartala,pune,3442).                   travel_dist(pune,agartala,3442).
travel_dist(agra,ahmedabad,878).                   travel_dist(ahmedabad,agra,878).
travel_dist(agra,bangalore,1848).                  travel_dist(bangalore,agra,1848).
travel_dist(agra,bhubaneshwar,1578).               travel_dist(bhubaneshwar,agra,1578).
travel_dist(agra,bombay,1202).                     travel_dist(bombay,agra,1202).
travel_dist(agra,calcutta,1300).                   travel_dist(calcutta,agra,1300).
travel_dist(agra,chandigarh,448).                  travel_dist(chandigarh,agra,448).
travel_dist(agra,cochin,2278).                     travel_dist(cochin,agra,2278).
travel_dist(agra,delhi,200).                       travel_dist(delhi,agra,200).
travel_dist(agra,hyderabad,1246).                  travel_dist(hyderabad,agra,1246).
travel_dist(agra,indore,591).                      travel_dist(indore,agra,591).
travel_dist(agra,jaipur,230).                      travel_dist(jaipur,agra,230).
travel_dist(agra,kanpur,290).                      travel_dist(kanpur,agra,290).
travel_dist(agra,lucknow,369).                     travel_dist(lucknow,agra,369).
travel_dist(agra,madras,2048).                     travel_dist(madras,agra,2048).
travel_dist(agra,nagpur,770).                      travel_dist(nagpur,agra,770).
travel_dist(agra,nasik,1005).                      travel_dist(nasik,agra,1005).
travel_dist(agra,panjim,1715).                     travel_dist(panjim,agra,1715).
travel_dist(agra,patna,885).                       travel_dist(patna,agra,885).
travel_dist(agra,pondicherry,2210).                travel_dist(pondicherry,agra,2210).
travel_dist(agra,pune,1214).                       travel_dist(pune,agra,1214).
travel_dist(ahmedabad,bangalore,1490).             travel_dist(bangalore,ahmedabad,1490).
travel_dist(ahmedabad,bhubaneshwar,1697).          travel_dist(bhubaneshwar,ahmedabad,1697).
travel_dist(ahmedabad,bombay,552).                 travel_dist(bombay,ahmedabad,552).
travel_dist(ahmedabad,calcutta,2068).              travel_dist(calcutta,ahmedabad,2068).
travel_dist(ahmedabad,chandigarh,1157).            travel_dist(chandigarh,ahmedabad,1157).
travel_dist(ahmedabad,cochin,1845).                travel_dist(cochin,ahmedabad,1845).
travel_dist(ahmedabad,delhi,911).                  travel_dist(delhi,ahmedabad,911).
travel_dist(ahmedabad,hyderabad,1436).             travel_dist(hyderabad,ahmedabad,1436).
travel_dist(ahmedabad,indore,442).                 travel_dist(indore,ahmedabad,442).
travel_dist(ahmedabad,jaipur,648).                 travel_dist(jaipur,ahmedabad,648).
travel_dist(ahmedabad,kanpur,1168).                travel_dist(kanpur,ahmedabad,1168).
travel_dist(ahmedabad,lucknow,1247).               travel_dist(lucknow,ahmedabad,1247).
travel_dist(ahmedabad,madras,1821).                travel_dist(madras,ahmedabad,1821).
travel_dist(ahmedabad,nagpur,965).                 travel_dist(nagpur,ahmedabad,965).
travel_dist(ahmedabad,nasik,504).                  travel_dist(nasik,ahmedabad,504).
travel_dist(ahmedabad,panjim,1165).                travel_dist(panjim,ahmedabad,1165).
travel_dist(ahmedabad,patna,1656).                 travel_dist(patna,ahmedabad,1656).
travel_dist(ahmedabad,pondicherry,1818).           travel_dist(pondicherry,ahmedabad,1818).
travel_dist(ahmedabad,pune,664).                   travel_dist(pune,ahmedabad,664).
travel_dist(allahabad,ahmedabad,1251).             travel_dist(ahmedabad,allahabad,1251).
travel_dist(allahabad,bangalore,1686).             travel_dist(bangalore,allahabad,1686).
travel_dist(allahabad,bhubaneshwar,1090).          travel_dist(bhubaneshwar,allahabad,1090).
travel_dist(allahabad,bombay,1457).                travel_dist(bombay,allahabad,1457).
travel_dist(allahabad,calcutta,817).               travel_dist(calcutta,allahabad,817).
travel_dist(allahabad,chandigarh,912).             travel_dist(chandigarh,allahabad,912).
travel_dist(allahabad,cochin,2216).                travel_dist(cochin,allahabad,2216).
travel_dist(allahabad,delhi,650).                  travel_dist(delhi,allahabad,650).
travel_dist(allahabad,hyderabad,1084).             travel_dist(hyderabad,allahabad,1084).
travel_dist(allahabad,indore,803).                 travel_dist(indore,allahabad,803).
travel_dist(allahabad,jaipur,713).                 travel_dist(jaipur,allahabad,713).
travel_dist(allahabad,kanpur,193).                 travel_dist(kanpur,allahabad,193).
travel_dist(allahabad,lucknow,234).                travel_dist(lucknow,allahabad,234).
travel_dist(allahabad,madras,2011).                travel_dist(madras,allahabad,2011).
travel_dist(allahabad,nagpur,608).                 travel_dist(nagpur,allahabad,608).
travel_dist(allahabad,nasik,1155).                 travel_dist(nasik,allahabad,1155).
travel_dist(allahabad,panjim,1419).                travel_dist(panjim,allahabad,1419).
travel_dist(allahabad,patna,402).                  travel_dist(patna,allahabad,402).
travel_dist(allahabad,pondicherry,1077).           travel_dist(pondicherry,allahabad,1077).
travel_dist(allahabad,pune,1364).                  travel_dist(pune,allahabad,1364).
travel_dist(amritsar,ahmedabad,1356).              travel_dist(ahmedabad,amritsar,1356).
travel_dist(amritsar,bangalore,2496).              travel_dist(bangalore,amritsar,2496).
travel_dist(amritsar,bhubaneshwar,2224).           travel_dist(bhubaneshwar,amritsar,2224).
travel_dist(amritsar,bombay,1849).                 travel_dist(bombay,amritsar,1849).
travel_dist(amritsar,calcutta,1919).               travel_dist(calcutta,amritsar,1919).
travel_dist(amritsar,chandigarh,239).              travel_dist(chandigarh,amritsar,239).
travel_dist(amritsar,cochin,3163).                 travel_dist(cochin,amritsar,3163).
travel_dist(amritsar,delhi,445).                   travel_dist(delhi,amritsar,445).
travel_dist(amritsar,hyderabad,1892).              travel_dist(hyderabad,amritsar,1892).
travel_dist(amritsar,indore,1258).                 travel_dist(indore,amritsar,1258).
travel_dist(amritsar,jaipur,706).                  travel_dist(jaipur,amritsar,706).
travel_dist(amritsar,kanpur,926).                  travel_dist(kanpur,amritsar,926).
travel_dist(amritsar,lucknow,939).                 travel_dist(lucknow,amritsar,939).
travel_dist(amritsar,madras,2688).                 travel_dist(madras,amritsar,2688).
travel_dist(amritsar,nagpur,1416).                 travel_dist(nagpur,amritsar,1416).
travel_dist(amritsar,nasik,1665).                  travel_dist(nasik,amritsar,1665).
travel_dist(amritsar,panjim,2237).                 travel_dist(panjim,amritsar,2237).
travel_dist(amritsar,patna,1531).                  travel_dist(patna,amritsar,1531).
travel_dist(amritsar,pondicherry,2856).            travel_dist(pondicherry,amritsar,2856).
travel_dist(amritsar,pune,1862).                   travel_dist(pune,amritsar,1862).
travel_dist(asansol,ahmedabad,1842).               travel_dist(ahmedabad,asansol,1842).
travel_dist(asansol,bangalore,2187).               travel_dist(bangalore,asansol,2187).
travel_dist(asansol,bhubaneshwar,523).             travel_dist(bhubaneshwar,asansol,523).
travel_dist(asansol,bombay,2040).                  travel_dist(bombay,asansol,2040).
travel_dist(asansol,calcutta,226).                 travel_dist(calcutta,asansol,226).
travel_dist(asansol,chandigarh,1503).              travel_dist(chandigarh,asansol,1503).
travel_dist(asansol,cochin,2544).                  travel_dist(cochin,asansol,2544).
travel_dist(asansol,delhi,1262).                   travel_dist(delhi,asansol,1262).
travel_dist(asansol,hyderabad,1693).               travel_dist(hyderabad,asansol,1693).
travel_dist(asansol,indore,1394).                  travel_dist(indore,asansol,1394).
travel_dist(asansol,jaipur,1304).                  travel_dist(jaipur,asansol,1304).
travel_dist(asansol,kanpur,789).                   travel_dist(kanpur,asansol,789).
travel_dist(asansol,lucknow,825).                  travel_dist(lucknow,asansol,825).
travel_dist(asansol,madras,1857).                  travel_dist(madras,asansol,1857).
travel_dist(asansol,nagpur,1122).                  travel_dist(nagpur,asansol,1122).
travel_dist(asansol,nasik,1746).                   travel_dist(nasik,asansol,1746).
travel_dist(asansol,panjim,2300).                  travel_dist(panjim,asansol,2300).
travel_dist(asansol,patna,395).                    travel_dist(patna,asansol,395).
travel_dist(asansol,pondicherry,2024).             travel_dist(pondicherry,asansol,2024).
travel_dist(asansol,pune,1955).                    travel_dist(pune,asansol,1955).
travel_dist(bangalore,ahmedabad,1490).             travel_dist(ahmedabad,bangalore,1490).
travel_dist(bangalore,bhubaneshwar,1538).          travel_dist(bhubaneshwar,bangalore,1538).
travel_dist(bangalore,bombay,1013).                travel_dist(bombay,bangalore,1013).
travel_dist(bangalore,calcutta,1961).              travel_dist(calcutta,bangalore,1961).
travel_dist(bangalore,chandigarh,2296).            travel_dist(chandigarh,bangalore,2296).
travel_dist(bangalore,cochin,512).                 travel_dist(cochin,bangalore,512).
travel_dist(bangalore,delhi,2049).                 travel_dist(delhi,bangalore,2049).
travel_dist(bangalore,hyderabad,563).              travel_dist(hyderabad,bangalore,563).
travel_dist(bangalore,indore,1601).                travel_dist(indore,bangalore,1601).
travel_dist(bangalore,jaipur,2005).                travel_dist(jaipur,bangalore,2005).
travel_dist(bangalore,kanpur,1855).                travel_dist(kanpur,bangalore,1855).
travel_dist(bangalore,lucknow,1934).               travel_dist(lucknow,bangalore,1934).
travel_dist(bangalore,madras,331).                 travel_dist(madras,bangalore,331).
travel_dist(bangalore,nagpur,1078).                travel_dist(nagpur,bangalore,1078).
travel_dist(bangalore,nasik,1035).                 travel_dist(nasik,bangalore,1035).
travel_dist(bangalore,panjim,440).                 travel_dist(panjim,bangalore,440).
travel_dist(bangalore,patna,2071).                 travel_dist(patna,bangalore,2071).
travel_dist(bangalore,pondicherry,328).            travel_dist(pondicherry,bangalore,328).
travel_dist(bangalore,pune,826).                   travel_dist(pune,bangalore,826).
travel_dist(baroda,ahmedabad,119).                 travel_dist(ahmedabad,baroda,119).
travel_dist(baroda,bangalore,1408).                travel_dist(bangalore,baroda,1408).
travel_dist(baroda,bhubaneshwar,1604).             travel_dist(bhubaneshwar,baroda,1604).
travel_dist(baroda,bombay,433).                    travel_dist(bombay,baroda,433).
travel_dist(baroda,calcutta,1937).                 travel_dist(calcutta,baroda,1937).
travel_dist(baroda,chandigarh,1181).               travel_dist(chandigarh,baroda,1181).
travel_dist(baroda,cochin,1763).                   travel_dist(cochin,baroda,1763).
travel_dist(baroda,delhi,1151).                    travel_dist(delhi,baroda,1151).
travel_dist(baroda,hyderabad,1127).                travel_dist(hyderabad,baroda,1127).
travel_dist(baroda,indore,379).                    travel_dist(indore,baroda,379).
travel_dist(baroda,jaipur,789).                    travel_dist(jaipur,baroda,789).
travel_dist(baroda,kanpur,1230).                   travel_dist(kanpur,baroda,1230).
travel_dist(baroda,lucknow,1311).                  travel_dist(lucknow,baroda,1311).
travel_dist(baroda,madras,1739).                   travel_dist(madras,baroda,1739).
travel_dist(baroda,nagpur,774).                    travel_dist(nagpur,baroda,774).
travel_dist(baroda,nasik,457).                     travel_dist(nasik,baroda,457).
travel_dist(baroda,panjim,1158).                   travel_dist(panjim,baroda,1158).
travel_dist(baroda,patna,1582).                    travel_dist(patna,baroda,1582).
travel_dist(baroda,pondicherry,1735).              travel_dist(pondicherry,baroda,1735).
travel_dist(baroda,pune,545).                      travel_dist(pune,baroda,545).
travel_dist(bhopal,ahmedabad,523).                 travel_dist(ahmedabad,bhopal,523).
travel_dist(bhopal,bangalore,1148).                travel_dist(bangalore,bhopal,1148).
travel_dist(bhopal,bhubaneshwar,1162).             travel_dist(bhubaneshwar,bhopal,1162).
travel_dist(bhopal,bombay,778).                    travel_dist(bombay,bhopal,778).
travel_dist(bhopal,calcutta,1495).                 travel_dist(calcutta,bhopal,1495).
travel_dist(bhopal,chandigarh,988).                travel_dist(chandigarh,bhopal,988).
travel_dist(bhopal,cochin,1995).                   travel_dist(cochin,bhopal,1995).
travel_dist(bhopal,delhi,742).                     travel_dist(delhi,bhopal,742).
travel_dist(bhopal,hyderabad,808).                 travel_dist(hyderabad,bhopal,808).
travel_dist(bhopal,indore,191).                    travel_dist(indore,bhopal,191).
travel_dist(bhopal,jaipur,596).                    travel_dist(jaipur,bhopal,596).
travel_dist(bhopal,kanpur,585).                    travel_dist(kanpur,bhopal,585).
travel_dist(bhopal,lucknow,664).                   travel_dist(lucknow,bhopal,664).
travel_dist(bhopal,madras,1604).                   travel_dist(madras,bhopal,1604).
travel_dist(bhopal,nagpur,352).                    travel_dist(nagpur,bhopal,352).
travel_dist(bhopal,nasik,605).                     travel_dist(nasik,bhopal,605).
travel_dist(bhopal,panjim,1143).                   travel_dist(panjim,bhopal,1143).
travel_dist(bhopal,patna,1016).                    travel_dist(patna,bhopal,1016).
travel_dist(bhopal,pondicherry,1772).              travel_dist(pondicherry,bhopal,1772).
travel_dist(bhopal,pune,814).                      travel_dist(pune,bhopal,814).
travel_dist(bhubaneshwar,ahmedabad,1647).          travel_dist(ahmedabad,bhubaneshwar,1647).
travel_dist(bhubaneshwar,bangalore,1538).          travel_dist(bangalore,bhubaneshwar,1538).
travel_dist(bhubaneshwar,bombay,1679).             travel_dist(bombay,bhubaneshwar,1679).
travel_dist(bhubaneshwar,calcutta,423).            travel_dist(calcutta,bhubaneshwar,423).
travel_dist(bhubaneshwar,chandigarh,2026).         travel_dist(chandigarh,bhubaneshwar,2026).
travel_dist(bhubaneshwar,cochin,1895).             travel_dist(cochin,bhubaneshwar,1895).
travel_dist(bhubaneshwar,delhi,1713).              travel_dist(delhi,bhubaneshwar,1713).
travel_dist(bhubaneshwar,hyderabad,1044).          travel_dist(hyderabad,bhubaneshwar,1044).
travel_dist(bhubaneshwar,indore,1355).             travel_dist(indore,bhubaneshwar,1355).
travel_dist(bhubaneshwar,jaipur,1758).             travel_dist(jaipur,bhubaneshwar,1758).
travel_dist(bhubaneshwar,kanpur,1283).             travel_dist(kanpur,bhubaneshwar,1283).
travel_dist(bhubaneshwar,lucknow,1254).            travel_dist(lucknow,bhubaneshwar,1254).
travel_dist(bhubaneshwar,madras,1207).             travel_dist(madras,bhubaneshwar,1207).
travel_dist(bhubaneshwar,nagpur,830).              travel_dist(nagpur,bhubaneshwar,830).
travel_dist(bhubaneshwar,nasik,1516).              travel_dist(nasik,bhubaneshwar,1516).
travel_dist(bhubaneshwar,panjim,1455).             travel_dist(panjim,bhubaneshwar,1455).
travel_dist(bhubaneshwar,patna,862).               travel_dist(patna,bhubaneshwar,862).
travel_dist(bhubaneshwar,pondicherry,1375).        travel_dist(pondicherry,bhubaneshwar,1375).
travel_dist(bhubaneshwar,pune,1587).               travel_dist(pune,bhubaneshwar,1587).
travel_dist(bombay,ahmedabad,552).                 travel_dist(ahmedabad,bombay,552).
travel_dist(bombay,bangalore,1013).                travel_dist(bangalore,bombay,1013).
travel_dist(bombay,bhubaneshwar,1678).             travel_dist(bhubaneshwar,bombay,1678).
travel_dist(bombay,calcutta,2012).                 travel_dist(calcutta,bombay,2012).
travel_dist(bombay,chandigarh,1645).               travel_dist(chandigarh,bombay,1645).
travel_dist(bombay,cochin,1368).                   travel_dist(cochin,bombay,1368).
travel_dist(bombay,delhi,1404).                    travel_dist(delhi,bombay,1404).
travel_dist(bombay,hyderabad,729).                 travel_dist(hyderabad,bombay,729).
travel_dist(bombay,indore,589).                    travel_dist(indore,bombay,589).
travel_dist(bombay,jaipur,1148).                   travel_dist(jaipur,bombay,1148).
travel_dist(bombay,kanpur,1278).                   travel_dist(kanpur,bombay,1278).
travel_dist(bombay,lucknow,1366).                  travel_dist(lucknow,bombay,1366).
travel_dist(bombay,madras,1344).                   travel_dist(madras,bombay,1344).
travel_dist(bombay,nagpur,849).                    travel_dist(nagpur,bombay,849).
travel_dist(bombay,nasik,197).                     travel_dist(nasik,bombay,197).
travel_dist(bombay,panjim,584).                    travel_dist(panjim,bombay,584).
travel_dist(bombay,patna,1856).                    travel_dist(patna,bombay,1856).
travel_dist(bombay,pondicherry,1452).              travel_dist(pondicherry,bombay,1452).
travel_dist(bombay,pune,184).                      travel_dist(pune,bombay,184).
travel_dist(calcutta,ahmedabad,2068).              travel_dist(ahmedabad,calcutta,2068).
travel_dist(calcutta,bangalore,1461).              travel_dist(bangalore,calcutta,1461).
travel_dist(calcutta,bhubaneshwar,423).            travel_dist(bhubaneshwar,calcutta,423).
travel_dist(calcutta,bombay,2012).                 travel_dist(bombay,calcutta,2012).
travel_dist(calcutta,chandigarh,1721).             travel_dist(chandigarh,calcutta,1721).
travel_dist(calcutta,cochin,2318).                 travel_dist(cochin,calcutta,2318).
travel_dist(calcutta,delhi,1474).                  travel_dist(delhi,calcutta,1474).
travel_dist(calcutta,hyderabad,1467).              travel_dist(hyderabad,calcutta,1467).
travel_dist(calcutta,indore,1620).                 travel_dist(indore,calcutta,1620).
travel_dist(calcutta,jaipur,1530).                 travel_dist(jaipur,calcutta,1530).
travel_dist(calcutta,kanpur,1010).                 travel_dist(kanpur,calcutta,1010).
travel_dist(calcutta,lucknow,1089).                travel_dist(lucknow,calcutta,1089).
travel_dist(calcutta,madras,1160).                 travel_dist(madras,calcutta,1160).
travel_dist(calcutta,nagpur,1163).                 travel_dist(nagpur,calcutta,1163).
travel_dist(calcutta,nasik,1849).                  travel_dist(nasik,calcutta,1849).
travel_dist(calcutta,panjim,974).                  travel_dist(panjim,calcutta,974).
travel_dist(calcutta,patna,621).                   travel_dist(patna,calcutta,621).
travel_dist(calcutta,pondicherry,1798).            travel_dist(pondicherry,calcutta,1798).
travel_dist(calcutta,pune,2058).                   travel_dist(pune,calcutta,2058).
travel_dist(calicut,ahmedabad,1648).               travel_dist(ahmedabad,calicut,1648).
travel_dist(calicut,bangalore,520).                travel_dist(bangalore,calicut,520).
travel_dist(calicut,bhubaneshwar,1923).            travel_dist(bhubaneshwar,calicut,1923).
travel_dist(calicut,bombay,1171).                  travel_dist(bombay,calicut,1171).
travel_dist(calicut,calcutta,2346).                travel_dist(calcutta,calicut,2346).
travel_dist(calicut,chandigarh,2741).              travel_dist(chandigarh,calicut,2741).
travel_dist(calicut,cochin,222).                   travel_dist(cochin,calicut,222).
travel_dist(calicut,delhi,2494).                   travel_dist(delhi,calicut,2494).
travel_dist(calicut,hyderabad,910).                travel_dist(hyderabad,calicut,910).
travel_dist(calicut,indore,1998).                  travel_dist(indore,calicut,1998).
travel_dist(calicut,jaipur,2523).                  travel_dist(jaipur,calicut,2523).
travel_dist(calicut,kanpur,2260).                  travel_dist(kanpur,calicut,2260).
travel_dist(calicut,lucknow,2339).                 travel_dist(lucknow,calicut,2339).
travel_dist(calicut,madras,715).                   travel_dist(madras,calicut,715).
travel_dist(calicut,nagpur,1483).                  travel_dist(nagpur,calicut,1483).
travel_dist(calicut,nasik,1193).                   travel_dist(nasik,calicut,1193).
travel_dist(calicut,panjim,576).                   travel_dist(panjim,calicut,576).
travel_dist(calicut,patna,2476).                   travel_dist(patna,calicut,2476).
travel_dist(calicut,pondicherry,566).              travel_dist(pondicherry,calicut,566).
travel_dist(calicut,pune,984).                     travel_dist(pune,calicut,984).
travel_dist(chandigarh,ahmedabad,1157).            travel_dist(ahmedabad,chandigarh,1157).
travel_dist(chandigarh,bangalore,2296).            travel_dist(bangalore,chandigarh,2296).
travel_dist(chandigarh,bhubaneshwar,2026).         travel_dist(bhubaneshwar,chandigarh,2026).
travel_dist(chandigarh,bombay,1645).               travel_dist(bombay,chandigarh,1645).
travel_dist(chandigarh,calcutta,1721).             travel_dist(calcutta,chandigarh,1721).
travel_dist(chandigarh,cochin,1965).               travel_dist(cochin,chandigarh,1965).
travel_dist(chandigarh,delhi,248).                 travel_dist(delhi,chandigarh,248).
travel_dist(chandigarh,hyderabad,1693).            travel_dist(hyderabad,chandigarh,1693).
travel_dist(chandigarh,indore,1052).               travel_dist(indore,chandigarh,1052).
travel_dist(chandigarh,jaipur,507).                travel_dist(jaipur,chandigarh,507).
travel_dist(chandigarh,kanpur,661).                travel_dist(kanpur,chandigarh,661).
travel_dist(chandigarh,lucknow,740).               travel_dist(lucknow,chandigarh,740).
travel_dist(chandigarh,madras,2489).               travel_dist(madras,chandigarh,2489).
travel_dist(chandigarh,nagpur,1217).               travel_dist(nagpur,chandigarh,1217).
travel_dist(chandigarh,nasik,1466).                travel_dist(nasik,chandigarh,1466).
travel_dist(chandigarh,panjim,2028).               travel_dist(panjim,chandigarh,2028).
travel_dist(chandigarh,patna,1332).                travel_dist(patna,chandigarh,1332).
travel_dist(chandigarh,pondicherry,2657).          travel_dist(pondicherry,chandigarh,2657).
travel_dist(chandigarh,pune,1663).                 travel_dist(pune,chandigarh,1663).
travel_dist(cochin,ahmedabad,1845).                travel_dist(ahmedabad,cochin,1845).
travel_dist(cochin,bangalore,512).                 travel_dist(bangalore,cochin,512).
travel_dist(cochin,bhubaneshwar,1895).             travel_dist(bhubaneshwar,cochin,1895).
travel_dist(cochin,bombay,1368).                   travel_dist(bombay,cochin,1368).
travel_dist(cochin,calcutta,2318).                 travel_dist(calcutta,cochin,2318).
travel_dist(cochin,chandigarh,1965).               travel_dist(chandigarh,cochin,1965).
travel_dist(cochin,delhi,2718).                    travel_dist(delhi,cochin,2718).
travel_dist(cochin,hyderabad,1090).                travel_dist(hyderabad,cochin,1090).
travel_dist(cochin,indore,1804).                   travel_dist(indore,cochin,1804).
travel_dist(cochin,jaipur,2745).                   travel_dist(jaipur,cochin,2745).
travel_dist(cochin,kanpur,2385).                   travel_dist(kanpur,cochin,2385).
travel_dist(cochin,lucknow,2572).                  travel_dist(lucknow,cochin,2572).
travel_dist(cochin,madras,687).                    travel_dist(madras,cochin,687).
travel_dist(cochin,nagpur,1608).                   travel_dist(nagpur,cochin,1608).
travel_dist(cochin,nasik,1390).                    travel_dist(nasik,cochin,1390).
travel_dist(cochin,panjim,798).                    travel_dist(panjim,cochin,798).
travel_dist(cochin,patna,2601).                    travel_dist(patna,cochin,2601).
travel_dist(cochin,pondicherry,530).               travel_dist(pondicherry,cochin,530).
travel_dist(cochin,pune,1181).                     travel_dist(pune,cochin,1181).
travel_dist(coimbatore,ahmedabad,1669).            travel_dist(ahmedabad,coimbatore,1669).
travel_dist(coimbatore,bangalore,333).             travel_dist(bangalore,coimbatore,333).
travel_dist(coimbatore,bhubaneshwar,1633).         travel_dist(bhubaneshwar,coimbatore,1633).
travel_dist(coimbatore,bombay,1192).               travel_dist(bombay,coimbatore,1192).
travel_dist(coimbatore,calcutta,2057).             travel_dist(calcutta,coimbatore,2057).
travel_dist(coimbatore,chandigarh,2669).           travel_dist(chandigarh,coimbatore,2669).
travel_dist(coimbatore,cochin,195).                travel_dist(cochin,coimbatore,195).
travel_dist(coimbatore,delhi,2412).                travel_dist(delhi,coimbatore,2412).
travel_dist(coimbatore,hyderabad,912).             travel_dist(hyderabad,coimbatore,912).
travel_dist(coimbatore,indore,1964).               travel_dist(indore,coimbatore,1964).
travel_dist(coimbatore,jaipur,2369).               travel_dist(jaipur,coimbatore,2369).
travel_dist(coimbatore,kanpur,2218).               travel_dist(kanpur,coimbatore,2218).
travel_dist(coimbatore,lucknow,2297).              travel_dist(lucknow,coimbatore,2297).
travel_dist(coimbatore,madras,426).                travel_dist(madras,coimbatore,426).
travel_dist(coimbatore,nagpur,1441).               travel_dist(nagpur,coimbatore,1441).
travel_dist(coimbatore,nasik,1214).                travel_dist(nasik,coimbatore,1214).
travel_dist(coimbatore,panjim,800).                travel_dist(panjim,coimbatore,800).
travel_dist(coimbatore,patna,2434).                travel_dist(patna,coimbatore,2434).
travel_dist(coimbatore,pondicherry,410).           travel_dist(pondicherry,coimbatore,410).
travel_dist(coimbatore,pune,1005).                 travel_dist(pune,coimbatore,1005).
travel_dist(delhi,ahmedabad,911).                  travel_dist(ahmedabad,delhi,911).
travel_dist(delhi,bangalore,2049).                 travel_dist(bangalore,delhi,2049).
travel_dist(delhi,bhubaneshwar,1713).              travel_dist(bhubaneshwar,delhi,1713).
travel_dist(delhi,bombay,1404).                    travel_dist(bombay,delhi,1404).
travel_dist(delhi,calcutta,1474).                  travel_dist(calcutta,delhi,1474).
travel_dist(delhi,chandigarh,248).                 travel_dist(chandigarh,delhi,248).
travel_dist(delhi,cochin,2718).                    travel_dist(cochin,delhi,2718).
travel_dist(delhi,hyderabad,1477).                 travel_dist(hyderabad,delhi,1477).
travel_dist(delhi,indore,806).                     travel_dist(indore,delhi,806).
travel_dist(delhi,jaipur,263).                     travel_dist(jaipur,delhi,263).
travel_dist(delhi,kanpur,481).                     travel_dist(kanpur,delhi,481).
travel_dist(delhi,lucknow,499).                    travel_dist(lucknow,delhi,499).
travel_dist(delhi,madras,2243).                    travel_dist(madras,delhi,2243).
travel_dist(delhi,nagpur,971).                     travel_dist(nagpur,delhi,971).
travel_dist(delhi,nasik,1220).                     travel_dist(nasik,delhi,1220).
travel_dist(delhi,panjim,1782).                    travel_dist(panjim,delhi,1782).
travel_dist(delhi,patna,1086).                     travel_dist(patna,delhi,1086).
travel_dist(delhi,pondicherry,2411).               travel_dist(pondicherry,delhi,2411).
travel_dist(delhi,pune,1417).                      travel_dist(pune,delhi,1417).
travel_dist(gwalior,ahmedabad,919).                travel_dist(ahmedabad,gwalior,919).
travel_dist(gwalior,bangalore,1734).               travel_dist(bangalore,gwalior,1734).
travel_dist(gwalior,bhubaneshwar,1486).            travel_dist(bhubaneshwar,gwalior,1486).
travel_dist(gwalior,bombay,1085).                  travel_dist(bombay,gwalior,1085).
travel_dist(gwalior,calcutta,1224).                travel_dist(calcutta,gwalior,1224).
travel_dist(gwalior,chandigarh,462).               travel_dist(chandigarh,gwalior,462).
travel_dist(gwalior,cochin,1881).                  travel_dist(cochin,gwalior,1881).
travel_dist(gwalior,delhi,315).                    travel_dist(delhi,gwalior,315).
travel_dist(gwalior,hyderabad,1132).               travel_dist(hyderabad,gwalior,1132).
travel_dist(gwalior,indore,497).                   travel_dist(indore,gwalior,497).
travel_dist(gwalior,jaipur,351).                   travel_dist(jaipur,gwalior,351).
travel_dist(gwalior,kanpur,280).                   travel_dist(kanpur,gwalior,280).
travel_dist(gwalior,lucknow,359).                  travel_dist(lucknow,gwalior,359).
travel_dist(gwalior,madras,1928).                  travel_dist(madras,gwalior,1928).
travel_dist(gwalior,nagpur,656).                   travel_dist(nagpur,gwalior,656).
travel_dist(gwalior,nasik,891).                    travel_dist(nasik,gwalior,891).
travel_dist(gwalior,panjim,1467).                  travel_dist(panjim,gwalior,1467).
travel_dist(gwalior,patna,809).                    travel_dist(patna,gwalior,809).
travel_dist(gwalior,pondicherry,2096).             travel_dist(pondicherry,gwalior,2096).
travel_dist(gwalior,pune,1100).                    travel_dist(pune,gwalior,1100).
travel_dist(hubli,ahmedabad,1101).                 travel_dist(ahmedabad,hubli,1101).
travel_dist(hubli,bangalore,391).                  travel_dist(bangalore,hubli,391).
travel_dist(hubli,bhubaneshwar,1620).              travel_dist(bhubaneshwar,hubli,1620).
travel_dist(hubli,bombay,614).                     travel_dist(bombay,hubli,614).
travel_dist(hubli,calcutta,2032).                  travel_dist(calcutta,hubli,2032).
travel_dist(hubli,chandigarh,2101).                travel_dist(chandigarh,hubli,2101).
travel_dist(hubli,cochin,774).                     travel_dist(cochin,hubli,774).
travel_dist(hubli,delhi,1854).                     travel_dist(delhi,hubli,1854).
travel_dist(hubli,hyderabad,486).                  travel_dist(hyderabad,hubli,486).
travel_dist(hubli,indore,1060).                    travel_dist(indore,hubli,1060).
travel_dist(hubli,jaipur,1060).                    travel_dist(jaipur,hubli,1060).
travel_dist(hubli,kanpur,1772).                    travel_dist(kanpur,hubli,1772).
travel_dist(hubli,lucknow,1851).                   travel_dist(lucknow,hubli,1851).
travel_dist(hubli,madras,683).                     travel_dist(madras,hubli,683).
travel_dist(hubli,nagpur,995).                     travel_dist(nagpur,hubli,995).
travel_dist(hubli,nasik,646).                      travel_dist(nasik,hubli,646).
travel_dist(hubli,panjim,190).                     travel_dist(panjim,hubli,190).
travel_dist(hubli,patna,1998).                     travel_dist(patna,hubli,1998).
travel_dist(hubli,pondicherry,653).                travel_dist(pondicherry,hubli,653).
travel_dist(hubli,pune,437).                       travel_dist(pune,hubli,437).
travel_dist(hyderabad,ahmedabad,1436).             travel_dist(ahmedabad,hyderabad,1436).
travel_dist(hyderabad,bangalore,563).              travel_dist(bangalore,hyderabad,563).
travel_dist(hyderabad,bhubaneshwar,1044).          travel_dist(bhubaneshwar,hyderabad,1044).
travel_dist(hyderabad,bombay,729).                 travel_dist(bombay,hyderabad,729).
travel_dist(hyderabad,calcutta,1467).              travel_dist(calcutta,hyderabad,1467).
travel_dist(hyderabad,chandigarh,1693).            travel_dist(chandigarh,hyderabad,1693).
travel_dist(hyderabad,cochin,1090).                travel_dist(cochin,hyderabad,1090).
travel_dist(hyderabad,delhi,1447).                 travel_dist(delhi,hyderabad,1447).
travel_dist(hyderabad,indore,999).                 travel_dist(indore,hyderabad,999).
travel_dist(hyderabad,jaipur,1404).                travel_dist(jaipur,hyderabad,1404).
travel_dist(hyderabad,kanpur,1253).                travel_dist(kanpur,hyderabad,1253).
travel_dist(hyderabad,lucknow,1332).               travel_dist(lucknow,hyderabad,1332).
travel_dist(hyderabad,madras,699).                 travel_dist(madras,hyderabad,699).
travel_dist(hyderabad,nagpur,476).                 travel_dist(nagpur,hyderabad,476).
travel_dist(hyderabad,nasik,754).                  travel_dist(nasik,hyderabad,754).
travel_dist(hyderabad,panjim,765).                 travel_dist(panjim,hyderabad,765).
travel_dist(hyderabad,patna,1469).                 travel_dist(patna,hyderabad,1469).
travel_dist(hyderabad,pondicherry,865).            travel_dist(pondicherry,hyderabad,865).
travel_dist(hyderabad,pune,545).                   travel_dist(pune,hyderabad,545).
travel_dist(imphal,ahmedabad,3240).                travel_dist(ahmedabad,imphal,3240).
travel_dist(imphal,bangalore,3677).                travel_dist(bangalore,imphal,3677).
travel_dist(imphal,bhubaneshwar,2139).             travel_dist(bhubaneshwar,imphal,2139).
travel_dist(imphal,bombay,3446).                   travel_dist(bombay,imphal,3446).
travel_dist(imphal,calcutta,1717).                 travel_dist(calcutta,imphal,1717).
travel_dist(imphal,chandigarh,2851).               travel_dist(chandigarh,imphal,2851).
travel_dist(imphal,cochin,4156).                   travel_dist(cochin,imphal,4156).
travel_dist(imphal,delhi,2561).                    travel_dist(delhi,imphal,2561).
travel_dist(imphal,hyderabad,3283).                travel_dist(hyderabad,imphal,3283).
travel_dist(imphal,indore,2744).                   travel_dist(indore,imphal,2744).
travel_dist(imphal,jaipur,2654).                   travel_dist(jaipur,imphal,2654).
travel_dist(imphal,kanpur,2134).                   travel_dist(kanpur,imphal,2134).
travel_dist(imphal,lucknow,2105).                  travel_dist(lucknow,imphal,2105).
travel_dist(imphal,madras,3326).                   travel_dist(madras,imphal,3326).
travel_dist(imphal,nagpur,2549).                   travel_dist(nagpur,imphal,2549).
travel_dist(imphal,nasik,3218).                    travel_dist(nasik,imphal,3218).
travel_dist(imphal,panjim,3360).                   travel_dist(panjim,imphal,3360).
travel_dist(imphal,patna,1534).                    travel_dist(patna,imphal,1534).
travel_dist(imphal,pondicherry,3614).              travel_dist(pondicherry,imphal,3614).
travel_dist(imphal,pune,3295).                     travel_dist(pune,imphal,3295).
travel_dist(indore,ahmedabad,442).                 travel_dist(ahmedabad,indore,442). 
travel_dist(indore,bangalore,1601).                travel_dist(bangalore,indore,1601).
travel_dist(indore,bhubaneshwar,1355).             travel_dist(bhubaneshwar,indore,1355).
travel_dist(indore,bombay,589).                    travel_dist(bombay,indore,589).
travel_dist(indore,calcutta,1620).                 travel_dist(calcutta,indore,1620).
travel_dist(indore,chandigarh,1052).               travel_dist(chandigarh,indore,1052).
travel_dist(indore,cochin,1804).                   travel_dist(cochin,indore,1804).
travel_dist(indore,delhi,806).                     travel_dist(delhi,indore,806).
travel_dist(indore,hyderabad,999).                 travel_dist(hyderabad,indore,999).
travel_dist(indore,jaipur,405).                    travel_dist(jaipur,indore,405).
travel_dist(indore,kanpur,689).                    travel_dist(kanpur,indore,689).
travel_dist(indore,lucknow,768).                   travel_dist(lucknow,indore,768).
travel_dist(indore,madras,1795).                   travel_dist(madras,indore,1795).
travel_dist(indore,nagpur,445).                    travel_dist(nagpur,indore,445).
travel_dist(indore,nasik,414).                     travel_dist(nasik,indore,414).
travel_dist(indore,panjim,1115).                   travel_dist(panjim,indore,1115).
travel_dist(indore,patna,1205).                    travel_dist(patna,indore,1205).                    
travel_dist(indore,pondicherry,1963).              travel_dist(pondicherry,indore,1963).
travel_dist(indore,pune,623).                      travel_dist(pune,indore,623).
travel_dist(jabalpur,ahmedabad,901).               travel_dist(ahmedabad,jabalpur,901).
travel_dist(jabalpur,bangalore,1335).              travel_dist(bangalore,jabalpur,1335).
travel_dist(jabalpur,bhubaneshwar,1087).           travel_dist(bhubaneshwar,jabalpur,1087).
travel_dist(jabalpur,bombay,1143).                 travel_dist(bombay,jabalpur,1143).
travel_dist(jabalpur,calcutta,1167).               travel_dist(calcutta,jabalpur,1167).
travel_dist(jabalpur,chandigarh,1046).             travel_dist(chandigarh,jabalpur,1046).
travel_dist(jabalpur,cochin,1885).                 travel_dist(cochin,jabalpur,1885).
travel_dist(jabalpur,delhi,800).                   travel_dist(delhi,jabalpur,800).
travel_dist(jabalpur,hyderabad,733).               travel_dist(hyderabad,jabalpur,733).
travel_dist(jabalpur,indore,859).                  travel_dist(indore,jabalpur,859).
travel_dist(jabalpur,jaipur,845).                  travel_dist(jaipur,jabalpur,845).
travel_dist(jabalpur,kanpur,543).                  travel_dist(kanpur,jabalpur,543).
travel_dist(jabalpur,lucknow,584).                 travel_dist(lucknow,jabalpur,584).
travel_dist(jabalpur,madras,1529).                 travel_dist(madras,jabalpur,1529).
travel_dist(jabalpur,nagpur,257).                  travel_dist(nagpur,jabalpur,257).
travel_dist(jabalpur,nasik,943).                   travel_dist(nasik,jabalpur,943).
travel_dist(jabalpur,panjim,1088).                 travel_dist(panjim,jabalpur,1088).
travel_dist(jabalpur,patna,736).                   travel_dist(patna,jabalpur,736).
travel_dist(jabalpur,pondicherry,1697).            travel_dist(pondicherry,jabalpur,1697).
travel_dist(jabalpur,pune,1003).                   travel_dist(pune,jabalpur,1003).
travel_dist(jaipur,ahmedabad,648).                 travel_dist(ahmedabad,jaipur,648).
travel_dist(jaipur,bangalore,2005).                travel_dist(bangalore,jaipur,2005).
travel_dist(jaipur,bhubaneshwar,1758).             travel_dist(bhubaneshwar,jaipur,1758).
travel_dist(jaipur,bombay,1148).                   travel_dist(bombay,jaipur,1148).
travel_dist(jaipur,calcutta,1530).                 travel_dist(calcutta,jaipur,1530).
travel_dist(jaipur,chandigarh,507).                travel_dist(chandigarh,jaipur,507).
travel_dist(jaipur,cochin,2745).                   travel_dist(cochin,jaipur,2745).
travel_dist(jaipur,delhi,263).                     travel_dist(delhi,jaipur,263).
travel_dist(jaipur,hyderabad,1404).                travel_dist(hyderabad,jaipur,1404).
travel_dist(jaipur,indore,405).                    travel_dist(indore,jaipur,405).
travel_dist(jaipur,kanpur,517).                    travel_dist(kanpur,jaipur,517).
travel_dist(jaipur,lucknow,598).                   travel_dist(lucknow,jaipur,598).
travel_dist(jaipur,madras,2200).                   travel_dist(madras,jaipur,2200).
travel_dist(jaipur,nagpur,928).                    travel_dist(nagpur,jaipur,928).
travel_dist(jaipur,nasik,1248).                    travel_dist(nasik,jaipur,1248).
travel_dist(jaipur,panjim,2496).                   travel_dist(panjim,jaipur,2496).
travel_dist(jaipur,patna,1115).                    travel_dist(patna,jaipur,1115).
travel_dist(jaipur,pondicherry,2368).              travel_dist(pondicherry,jaipur,2368).
travel_dist(jaipur,pune,1371).                     travel_dist(pune,jaipur,1371).
travel_dist(jamshedpur,ahmedabad,1225).            travel_dist(ahmedabad,jamshedpur,1225).
travel_dist(jamshedpur,bangalore,1690).            travel_dist(bangalore,jamshedpur,1690).
travel_dist(jamshedpur,bhubaneshwar,422).          travel_dist(bhubaneshwar,jamshedpur,422).
travel_dist(jamshedpur,bombay,1916).               travel_dist(bombay,jamshedpur,1916).
travel_dist(jamshedpur,calcutta,268).              travel_dist(calcutta,jamshedpur,268).
travel_dist(jamshedpur,chandigarh,1602).           travel_dist(chandigarh,jamshedpur,1602).
travel_dist(jamshedpur,cochin,2710).               travel_dist(cochin,jamshedpur,2710).
travel_dist(jamshedpur,delhi,1356).                travel_dist(delhi,jamshedpur,1356).
travel_dist(jamshedpur,hyderabad,1578).            travel_dist(hyderabad,jamshedpur,1578).
travel_dist(jamshedpur,indore,1477).               travel_dist(indore,jamshedpur,1477).
travel_dist(jamshedpur,jaipur,1387).               travel_dist(jaipur,jamshedpur,1387).
travel_dist(jamshedpur,kanpur,867).                travel_dist(kanpur,jamshedpur,867).
travel_dist(jamshedpur,lucknow,1121).              travel_dist(lucknow,jamshedpur,1121).
travel_dist(jamshedpur,madras,1629).               travel_dist(madras,jamshedpur,1629).
travel_dist(jamshedpur,nagpur,1102).               travel_dist(nagpur,jamshedpur,1102).
travel_dist(jamshedpur,nasik,1788).                travel_dist(nasik,jamshedpur,1788).
travel_dist(jamshedpur,panjim,2229).               travel_dist(panjim,jamshedpur,2229).
travel_dist(jamshedpur,patna,473).                 travel_dist(patna,jamshedpur,473).
travel_dist(jamshedpur,pondicherry,1797).          travel_dist(pondicherry,jamshedpur,1797).
travel_dist(jamshedpur,pune,1997).                 travel_dist(pune,jamshedpur,1997).
travel_dist(jullundur,ahmedabad,1285).             travel_dist(ahmedabad,jullundur,1285).
travel_dist(jullundur,bangalore,2416).             travel_dist(bangalore,jullundur,2416).
travel_dist(jullundur,bhubaneshwar,2413).          travel_dist(bhubaneshwar,jullundur,2413).
travel_dist(jullundur,bombay,1778).                travel_dist(bombay,jullundur,1778).
travel_dist(jullundur,calcutta,1869).              travel_dist(calcutta,jullundur,1869).
travel_dist(jullundur,chandigarh,154).             travel_dist(chandigarh,jullundur,154).
travel_dist(jullundur,cochin,3082).                travel_dist(cochin,jullundur,3082).
travel_dist(jullundur,delhi,375).                  travel_dist(delhi,jullundur,375).
travel_dist(jullundur,hyderabad,1821).             travel_dist(hyderabad,jullundur,1821).
travel_dist(jullundur,indore,1171).                travel_dist(indore,jullundur,1171).
travel_dist(jullundur,jaipur,891).                 travel_dist(jaipur,jullundur,891).
travel_dist(jullundur,kanpur,855).                 travel_dist(kanpur,jullundur,855).
travel_dist(jullundur,lucknow,868).                travel_dist(lucknow,jullundur,868).
travel_dist(jullundur,madras,2617).                travel_dist(madras,jullundur,2617).
travel_dist(jullundur,nagpur,1354).                travel_dist(nagpur,jullundur,1354).
travel_dist(jullundur,nasik,1591).                 travel_dist(nasik,jullundur,1591).
travel_dist(jullundur,panjim,2146).                travel_dist(panjim,jullundur,2146).
travel_dist(jullundur,patna,1460).                 travel_dist(patna,jullundur,1460).
travel_dist(jullundur,pondicherry,2785).           travel_dist(pondicherry,jullundur,2785).
travel_dist(jullundur,pune,1791).                  travel_dist(pune,jullundur,1791).
travel_dist(kanpur,ahmedabad,1168).                travel_dist(ahmedabad,kanpur,1168).
travel_dist(kanpur,bangalore,1855).                travel_dist(bangalore,kanpur,1855).
travel_dist(kanpur,bhubaneshwar,1283).             travel_dist(bhubaneshwar,kanpur,1283).
travel_dist(kanpur,bombay,1278).                   travel_dist(bombay,kanpur,1278).
travel_dist(kanpur,calcutta,1010).                 travel_dist(calcutta,kanpur,1010).
travel_dist(kanpur,chandigarh,661).                travel_dist(chandigarh,kanpur,661).
travel_dist(kanpur,cochin,2385).                   travel_dist(cochin,kanpur,2385).
travel_dist(kanpur,delhi,481).                     travel_dist(delhi,kanpur,481).
travel_dist(kanpur,hyderabad,1253).                travel_dist(hyderabad,kanpur,1253).
travel_dist(kanpur,indore,689).                    travel_dist(indore,kanpur,689).
travel_dist(kanpur,jaipur,517).                    travel_dist(jaipur,kanpur,517).
travel_dist(kanpur,lucknow,79).                    travel_dist(lucknow,kanpur,79).
travel_dist(kanpur,madras,2049).                   travel_dist(madras,kanpur,2049).
travel_dist(kanpur,nagpur,777).                    travel_dist(nagpur,kanpur,777).
travel_dist(kanpur,nasik,1103).                    travel_dist(nasik,kanpur,1103).
travel_dist(kanpur,panjim,1813).                   travel_dist(panjim,kanpur,1813).
travel_dist(kanpur,patna,596).                     travel_dist(patna,kanpur,596).
travel_dist(kanpur,pondicherry,2217).              travel_dist(pondicherry,kanpur,2217).
travel_dist(kanpur,pune,1312).                     travel_dist(pune,kanpur,1312).
travel_dist(kolhapur,ahmedabad,911).               travel_dist(ahmedabad,kolhapur,911).
travel_dist(kolhapur,bangalore,484).               travel_dist(bangalore,kolhapur,484).
travel_dist(kolhapur,bhubaneshwar,1622).           travel_dist(bhubaneshwar,kolhapur,1622).
travel_dist(kolhapur,bombay,426).                  travel_dist(bombay,kolhapur,426).
travel_dist(kolhapur,calcutta,2045).               travel_dist(calcutta,kolhapur,2045).
travel_dist(kolhapur,chandigarh,1910).             travel_dist(chandigarh,kolhapur,1910).
travel_dist(kolhapur,cochin,934).                  travel_dist(cochin,kolhapur,934).
travel_dist(kolhapur,delhi,1664).                  travel_dist(delhi,kolhapur,1664).
travel_dist(kolhapur,hyderabad,578).               travel_dist(hyderabad,kolhapur,578).
travel_dist(kolhapur,indore,870).                  travel_dist(indore,kolhapur,870).
travel_dist(kolhapur,jaipur,1518).                 travel_dist(jaipur,kolhapur,1518).
travel_dist(kolhapur,kanpur,1779).                 travel_dist(kanpur,kolhapur,1779).
travel_dist(kolhapur,lucknow,1858).                travel_dist(lucknow,kolhapur,1858).
travel_dist(kolhapur,madras,910).                  travel_dist(madras,kolhapur,910).
travel_dist(kolhapur,nagpur,1050).                 travel_dist(nagpur,kolhapur,1050).
travel_dist(kolhapur,nasik,456).                   travel_dist(nasik,kolhapur,456).
travel_dist(kolhapur,panjim,254).                  travel_dist(panjim,kolhapur,254).
travel_dist(kolhapur,patna,2047).                  travel_dist(patna,kolhapur,2047).
travel_dist(kolhapur,pondicherry,907).             travel_dist(pondicherry,kolhapur,907).
travel_dist(kolhapur,pune,247).                    travel_dist(pune,kolhapur,247).
travel_dist(lucknow,ahmedabad,1247).               travel_dist(ahmedabad,lucknow,1247).
travel_dist(lucknow,bangalore,1934).               travel_dist(bangalore,lucknow,1934).
travel_dist(lucknow,bhubaneshwar,1254).            travel_dist(bhubaneshwar,lucknow,1254).
travel_dist(lucknow,bombay,1366).                  travel_dist(bombay,lucknow,1366).
travel_dist(lucknow,calcutta,1089).                travel_dist(calcutta,lucknow,1089).
travel_dist(lucknow,chandigarh,740).               travel_dist(chandigarh,lucknow,740).
travel_dist(lucknow,cochin,2572).                  travel_dist(cochin,lucknow,2572).
travel_dist(lucknow,delhi,499).                    travel_dist(delhi,lucknow,499).
travel_dist(lucknow,hyderabad,1332).               travel_dist(hyderabad,lucknow,1332).
travel_dist(lucknow,indore,768).                   travel_dist(indore,lucknow,768).
travel_dist(lucknow,jaipur,598).                   travel_dist(jaipur,lucknow,598).
travel_dist(lucknow,kanpur,79).                    travel_dist(kanpur,lucknow,79).
travel_dist(lucknow,madras,2128).                  travel_dist(madras,lucknow,2128).
travel_dist(lucknow,nagpur,856).                   travel_dist(nagpur,lucknow,856).
travel_dist(lucknow,nasik,1182).                   travel_dist(nasik,lucknow,1182).
travel_dist(lucknow,panjim,1883).                  travel_dist(panjim,lucknow,1883).
travel_dist(lucknow,patna,566).                    travel_dist(patna,lucknow,566).
travel_dist(lucknow,pondicherry,2296).             travel_dist(pondicherry,lucknow,2296).
travel_dist(lucknow,pune,1391).                    travel_dist(pune,lucknow,1391).
travel_dist(ludhiana,ahmedabad,1220).              travel_dist(ahmedabad,ludhiana,1220).
travel_dist(ludhiana,bangalore,2358).              travel_dist(bangalore,ludhiana,2358).
travel_dist(ludhiana,bhubaneshwar,2088).           travel_dist(bhubaneshwar,ludhiana,2088).
travel_dist(ludhiana,bombay,1770).                 travel_dist(bombay,ludhiana,1770).
travel_dist(ludhiana,calcutta,1783).               travel_dist(calcutta,ludhiana,1783).
travel_dist(ludhiana,chandigarh,105).              travel_dist(chandigarh,ludhiana,105).
travel_dist(ludhiana,cochin,3027).                 travel_dist(cochin,ludhiana,3027).
travel_dist(ludhiana,delhi,310).                   travel_dist(delhi,ludhiana,310).
travel_dist(ludhiana,hyderabad,1756).              travel_dist(hyderabad,ludhiana,1756).
travel_dist(ludhiana,indore,1115).                 travel_dist(indore,ludhiana,1115).
travel_dist(ludhiana,jaipur,570).                  travel_dist(jaipur,ludhiana,570).
travel_dist(ludhiana,kanpur,790).                  travel_dist(kanpur,ludhiana,790).
travel_dist(ludhiana,lucknow,803).                 travel_dist(lucknow,ludhiana,803).
travel_dist(ludhiana,madras,2552).                 travel_dist(madras,ludhiana,2552).
travel_dist(ludhiana,nagpur,1280).                 travel_dist(nagpur,ludhiana,1280).
travel_dist(ludhiana,nasik,1528).                  travel_dist(nasik,ludhiana,1528).
travel_dist(ludhiana,panjim,2091).                 travel_dist(panjim,ludhiana,2091).
travel_dist(ludhiana,patna,1395).                  travel_dist(patna,ludhiana,1395).
travel_dist(ludhiana,pondicherry,2720).            travel_dist(pondicherry,ludhiana,2720).
travel_dist(ludhiana,pune,1726).                   travel_dist(pune,ludhiana,1726).
travel_dist(madras,ahmedabad,1821).                travel_dist(ahmedabad,madras,1821).
travel_dist(madras,bangalore,331).                 travel_dist(bangalore,madras,331).
travel_dist(madras,bhubaneshwar,1207).             travel_dist(bhubaneshwar,madras,1207).
travel_dist(madras,bombay,1344).                   travel_dist(bombay,madras,1344).
travel_dist(madras,calcutta,1630).                 travel_dist(calcutta,madras,1630).
travel_dist(madras,chandigarh,2489).               travel_dist(chandigarh,madras,2489).
travel_dist(madras,cochin,687).                    travel_dist(cochin,madras,687).
travel_dist(madras,delhi,2243).                    travel_dist(delhi,madras,2243).
travel_dist(madras,hyderabad,699).                 travel_dist(hyderabad,madras,699).
travel_dist(madras,indore,1795).                   travel_dist(indore,madras,1795).
travel_dist(madras,jaipur,2200).                   travel_dist(jaipur,madras,2200).
travel_dist(madras,kanpur,2049).                   travel_dist(kanpur,madras,2049).
travel_dist(madras,lucknow,2128).                  travel_dist(lucknow,madras,2128).
travel_dist(madras,nagpur,1272).                   travel_dist(nagpur,madras,1272).
travel_dist(madras,nasik,1366).                    travel_dist(nasik,madras,1366).
travel_dist(madras,panjim,909).                    travel_dist(panjim,madras,909).
travel_dist(madras,patna,2096).                    travel_dist(patna,madras,2096).
travel_dist(madras,pondicherry,168).               travel_dist(pondicherry,madras,168).
travel_dist(madras,pune,1157).                     travel_dist(pune,madras,1157).
travel_dist(madurai,ahmedabad,1922).               travel_dist(ahmedabad,madurai,1922).
travel_dist(madurai,bangalore,432).                travel_dist(bangalore,madurai,432).
travel_dist(madurai,bhubaneshwar,1687).            travel_dist(bhubaneshwar,madurai,1687).
travel_dist(madurai,bombay,1458).                  travel_dist(bombay,madurai,1458).
travel_dist(madurai,calcutta,2110).                travel_dist(calcutta,madurai,2110).
travel_dist(madurai,chandigarh,2785).              travel_dist(chandigarh,madurai,2785).
travel_dist(madurai,cochin,326).                   travel_dist(cochin,madurai,326).
travel_dist(madurai,delhi,2539).                   travel_dist(delhi,madurai,2539).
travel_dist(madurai,hyderabad,995).                travel_dist(hyderabad,madurai,995).
travel_dist(madurai,indore,2091).                  travel_dist(indore,madurai,2091).
travel_dist(madurai,jaipur,2496).                  travel_dist(jaipur,madurai,2496).
travel_dist(madurai,kanpur,2345).                  travel_dist(kanpur,madurai,2345).
travel_dist(madurai,lucknow,2424).                 travel_dist(lucknow,madurai,2424).
travel_dist(madurai,madras,480).                   travel_dist(madras,madurai,480).
travel_dist(madurai,nagpur,1568).                  travel_dist(nagpur,madurai,1568).
travel_dist(madurai,nasik,1467).                   travel_dist(nasik,madurai,1467).
travel_dist(madurai,panjim,872).                   travel_dist(panjim,madurai,872).
travel_dist(madurai,patna,2561).                   travel_dist(patna,madurai,2561).
travel_dist(madurai,pondicherry,333).              travel_dist(pondicherry,madurai,333).
travel_dist(madurai,pune,1238).                    travel_dist(pune,madurai,1238).
travel_dist(meerut,ahmedabad,1092).                travel_dist(ahmedabad,meerut,1092).
travel_dist(meerut,bangalore,2072).                travel_dist(bangalore,meerut,2072).
travel_dist(meerut,bhubaneshwar,1822).             travel_dist(bhubaneshwar,meerut,1822).
travel_dist(meerut,bombay,1468).                   travel_dist(bombay,meerut,1468).
travel_dist(meerut,calcutta,1497).                 travel_dist(calcutta,meerut,1497).
travel_dist(meerut,chandigarh,381).                travel_dist(chandigarh,meerut,381).
travel_dist(meerut,cochin,2741).                   travel_dist(cochin,meerut,2741).
travel_dist(meerut,delhi,66).                      travel_dist(delhi,meerut,66).
travel_dist(meerut,hyderabad,1470).                travel_dist(hyderabad,meerut,1470).
travel_dist(meerut,indore,815).                    travel_dist(indore,meerut,815).
travel_dist(meerut,jaipur,327).                    travel_dist(jaipur,meerut,327).
travel_dist(meerut,kanpur,537).                    travel_dist(kanpur,meerut,537).
travel_dist(meerut,lucknow,453).                   travel_dist(lucknow,meerut,453).
travel_dist(meerut,madras,2266).                   travel_dist(madras,meerut,2266).
travel_dist(meerut,nagpur,994).                    travel_dist(nagpur,meerut,994).
travel_dist(meerut,nasik,1242).                    travel_dist(nasik,meerut,1242).
travel_dist(meerut,panjim,1805).                   travel_dist(panjim,meerut,1805).
travel_dist(meerut,patna,934).                     travel_dist(patna,meerut,934).
travel_dist(meerut,pondicherry,2434).              travel_dist(pondicherry,meerut,2434).
travel_dist(meerut,pune,1440).                     travel_dist(pune,meerut,1440).
travel_dist(nagpur,ahmedabad,965).                 travel_dist(ahmedabad,nagpur,965).
travel_dist(nagpur,bangalore,1078).                travel_dist(bangalore,nagpur,1078).
travel_dist(nagpur,bhubaneshwar,830).              travel_dist(bhubaneshwar,nagpur,830).
travel_dist(nagpur,bombay,849).                    travel_dist(bombay,nagpur,849).
travel_dist(nagpur,calcutta,1163).                 travel_dist(calcutta,nagpur,1163).
travel_dist(nagpur,chandigarh,1217).               travel_dist(chandigarh,nagpur,1217).
travel_dist(nagpur,cochin,1608).                   travel_dist(cochin,nagpur,1608).
travel_dist(nagpur,delhi,971).                     travel_dist(delhi,nagpur,971).
travel_dist(nagpur,hyderabad,476).                 travel_dist(hyderabad,nagpur,476).
travel_dist(nagpur,indore,445).                    travel_dist(indore,nagpur,445).
travel_dist(nagpur,jaipur,928).                    travel_dist(jaipur,nagpur,928).
travel_dist(nagpur,kanpur,777).                    travel_dist(kanpur,nagpur,777).
travel_dist(nagpur,lucknow,856).                   travel_dist(lucknow,nagpur,856).
travel_dist(nagpur,madras,1272).                   travel_dist(madras,nagpur,1272).
travel_dist(nagpur,nasik,700).                     travel_dist(nasik,nagpur,700).
travel_dist(nagpur,panjim,1247).                   travel_dist(panjim,nagpur,1247).
travel_dist(nagpur,patna,993).                     travel_dist(patna,nagpur,993).
travel_dist(nagpur,pondicherry,1440).              travel_dist(pondicherry,nagpur,1440).
travel_dist(nagpur,pune,909).                      travel_dist(pune,nagpur,909).
travel_dist(nasik,ahmedabad,504).                  travel_dist(ahmedabad,nasik,504).
travel_dist(nasik,bangalore,1036).                 travel_dist(bangalore,nasik,1036).
travel_dist(nasik,bhubaneshwar,1516).              travel_dist(bhubaneshwar,nasik,1516).
travel_dist(nasik,bombay,197).                     travel_dist(bombay,nasik,197).
travel_dist(nasik,calcutta,1849).                  travel_dist(calcutta,nasik,1849).
travel_dist(nasik,chandigarh,1466).                travel_dist(chandigarh,nasik,1466).
travel_dist(nasik,cochin,1390).                    travel_dist(cochin,nasik,1390).
travel_dist(nasik,delhi,1220).                     travel_dist(delhi,nasik,1220).
travel_dist(nasik,hyderabad,754).                  travel_dist(hyderabad,nasik,754).
travel_dist(nasik,indore,414).                     travel_dist(indore,nasik,414).
travel_dist(nasik,jaipur,1246).                    travel_dist(jaipur,nasik,1246).
travel_dist(nasik,kanpur,1103).                    travel_dist(kanpur,nasik,1103).
travel_dist(nasik,lucknow,1182).                   travel_dist(lucknow,nasik,1182).
travel_dist(nasik,madras,1366).                    travel_dist(madras,nasik,1366).
travel_dist(nasik,nagpur,700).                     travel_dist(nagpur,nasik,700).
travel_dist(nasik,panjim,701).                     travel_dist(panjim,nasik,701).
travel_dist(nasik,patna,1679).                     travel_dist(patna,nasik,1679).
travel_dist(nasik,pondicherry,1363).               travel_dist(pondicherry,nasik,1363).
travel_dist(nasik,pune,209).                       travel_dist(pune,nasik,209).
travel_dist(panjim,ahmedabad,1165).                travel_dist(ahmedabad,panjim,1165).
travel_dist(panjim,bangalore,440).                 travel_dist(bangalore,panjim,440).
travel_dist(panjim,bhubaneshwar,1455).             travel_dist(bhubaneshwar,panjim,1455).
travel_dist(panjim,bombay,584).                    travel_dist(bombay,panjim,584).
travel_dist(panjim,calcutta,974).                  travel_dist(calcutta,panjim,974).
travel_dist(panjim,chandigarh,2028).               travel_dist(chandigarh,panjim,2028).
travel_dist(panjim,cochin,798).                    travel_dist(cochin,panjim,798).
travel_dist(panjim,delhi,1782).                    travel_dist(delhi,panjim,1782).
travel_dist(panjim,hyderabad,765).                 travel_dist(hyderabad,panjim,765).
travel_dist(panjim,indore,1115).                   travel_dist(indore,panjim,1115).
travel_dist(panjim,jaipur,2496).                   travel_dist(jaipur,panjim,2496).
travel_dist(panjim,kanpur,1813).                   travel_dist(kanpur,panjim,1813).   
travel_dist(panjim,lucknow,1883).                  travel_dist(lucknow,panjim,1883).
travel_dist(panjim,madras,909).                    travel_dist(madras,panjim,909).
travel_dist(panjim,nagpur,1247).                   travel_dist(nagpur,panjim,1247).
travel_dist(panjim,nasik,701).                     travel_dist(nasik,panjim,701).
travel_dist(panjim,patna,1804).                    travel_dist(patna,panjim,1804).
travel_dist(panjim,pondicherry,739).               travel_dist(pondicherry,panjim,739).
travel_dist(panjim,pune,501).                      travel_dist(pune,panjim,501).
travel_dist(patna,ahmedabad,1656).                 travel_dist(ahmedabad,patna,1656).
travel_dist(patna,bangalore,2071).                 travel_dist(bangalore,patna,2071).
travel_dist(patna,bhubaneshwar,862).               travel_dist(bhubaneshwar,patna,862).
travel_dist(patna,bombay,1856).                    travel_dist(bombay,patna,1856).
travel_dist(patna,calcutta,621).                   travel_dist(calcutta,patna,621).
travel_dist(patna,chandigarh,1332).                travel_dist(chandigarh,patna,1332).
travel_dist(patna,cochin,2601).                    travel_dist(cochin,patna,2601).
travel_dist(patna,delhi,1086).                     travel_dist(delhi,patna,1086).
travel_dist(patna,hyderabad,1489).                 travel_dist(hyderabad,patna,1489).
travel_dist(patna,indore,1205).                    travel_dist(indore,patna,1205).
travel_dist(patna,jaipur,1115).                    travel_dist(jaipur,patna,1115).
travel_dist(patna,kanpur,595).                     travel_dist(kanpur,patna,595).
travel_dist(patna,lucknow,566).                    travel_dist(lucknow,patna,566).
travel_dist(patna,madras,2096).                    travel_dist(madras,patna,2096).
travel_dist(patna,nagpur,993).                     travel_dist(nagpur,patna,993).
travel_dist(patna,nasik,1679).                     travel_dist(nasik,patna,1679).
travel_dist(patna,panjim,1804).                    travel_dist(panjim,patna,1804).
travel_dist(patna,pondicherry,2264).               travel_dist(pondicherry,patna,2264).
travel_dist(patna,pune,1738).                      travel_dist(pune,patna,1738).
travel_dist(pondicherry,ahmedabad,1818).           travel_dist(ahmedabad,pondicherry,1818).
travel_dist(pondicherry,bangalore,328).            travel_dist(bangalore,pondicherry,328).
travel_dist(pondicherry,bhubaneshwar,1375).        travel_dist(bhubaneshwar,pondicherry,1375).
travel_dist(pondicherry,bombay,1452).              travel_dist(bombay,pondicherry,1452).
travel_dist(pondicherry,calcutta,1798).            travel_dist(calcutta,pondicherry,1798).
travel_dist(pondicherry,chandigarh,2657).          travel_dist(chandigarh,pondicherry,2657).
travel_dist(pondicherry,cochin,530).               travel_dist(cochin,pondicherry,530).
travel_dist(pondicherry,delhi,2411).               travel_dist(delhi,pondicherry,2411).
travel_dist(pondicherry,hyderabad,867).            travel_dist(hyderabad,pondicherry,867).
travel_dist(pondicherry,indore,1963).              travel_dist(indore,pondicherry,1963).
travel_dist(pondicherry,jaipur,2368).              travel_dist(jaipur,pondicherry,2368).
travel_dist(pondicherry,kanpur,2217).              travel_dist(kanpur,pondicherry,2217).
travel_dist(pondicherry,lucknow,2296).             travel_dist(lucknow,pondicherry,2296).
travel_dist(pondicherry,madras,168).               travel_dist(madras,pondicherry,168).
travel_dist(pondicherry,nagpur,1440).              travel_dist(nagpur,pondicherry,1440).
travel_dist(pondicherry,nasik,1363).               travel_dist(nasik,pondicherry,1363).
travel_dist(pondicherry,panjim,739).               travel_dist(panjim,pondicherry,739).
travel_dist(pondicherry,patna,2264).               travel_dist(patna,pondicherry,2264).
travel_dist(pondicherry,pune,1154).                travel_dist(pune,pondicherry,1154).
travel_dist(pune,ahmedabad,664).                   travel_dist(ahmedabad,pune,664).
travel_dist(pune,bangalore,826).                   travel_dist(bangalore,pune,826).
travel_dist(pune,bhubaneshwar,1587).               travel_dist(bhubaneshwar,pune,1587).
travel_dist(pune,bombay,184).                      travel_dist(bombay,pune,184).
travel_dist(pune,calcutta,2058).                   travel_dist(calcutta,pune,2058).
travel_dist(pune,chandigarh,1663).                 travel_dist(chandigarh,pune,1663).
travel_dist(pune,cochin,1181).                     travel_dist(cochin,pune,1181).
travel_dist(pune,delhi,1417).                      travel_dist(delhi,pune,1417).
travel_dist(pune,hyderabad,545).                   travel_dist(hyderabad,pune,545).
travel_dist(pune,indore,623).                      travel_dist(indore,pune,623).
travel_dist(pune,jaipur,1371).                     travel_dist(jaipur,pune,1371).
travel_dist(pune,kanpur,1312).                     travel_dist(kanpur,pune,1312).
travel_dist(pune,lucknow,1391).                    travel_dist(lucknow,pune,1391).
travel_dist(pune,madras,1157).                     travel_dist(madras,pune,1157).
travel_dist(pune,nagpur,909).                      travel_dist(nagpur,pune,909).
travel_dist(pune,nasik,209).                       travel_dist(nasik,pune,209).
travel_dist(pune,panjim,501).                      travel_dist(panjim,pune,501).
travel_dist(pune,patna,1738).                      travel_dist(patna,pune,1738).
travel_dist(pune,pondicherry,1154).                travel_dist(pondicherry,pune,1154).
travel_dist(ranchi,ahmedabad,1781).                travel_dist(ahmedabad,ranchi,1781).
travel_dist(ranchi,bangalore,2098).                travel_dist(bangalore,ranchi,2098).
travel_dist(ranchi,bhubaneshwar,560).              travel_dist(bhubaneshwar,ranchi,560).
travel_dist(ranchi,bombay,1816).                   travel_dist(bombay,ranchi,1816).
travel_dist(ranchi,calcutta,414).                  travel_dist(calcutta,ranchi,414).
travel_dist(ranchi,chandigarh,1480).               travel_dist(chandigarh,ranchi,1480).
travel_dist(ranchi,cochin,2455).                   travel_dist(cochin,ranchi,2455).
travel_dist(ranchi,delhi,1214).                    travel_dist(delhi,ranchi,1214).
travel_dist(ranchi,hyderabad,1434).                travel_dist(hyderabad,ranchi,1434).
travel_dist(ranchi,indore,1333).                   travel_dist(indore,ranchi,1333).
travel_dist(ranchi,jaipur,1243).                   travel_dist(jaipur,ranchi,1243).
travel_dist(ranchi,kanpur,723).                    travel_dist(kanpur,ranchi,723).
travel_dist(ranchi,lucknow,912).                   travel_dist(lucknow,ranchi,912).
travel_dist(ranchi,madras,1767).                   travel_dist(madras,ranchi,1767).
travel_dist(ranchi,nagpur,958).                    travel_dist(nagpur,ranchi,958).
travel_dist(ranchi,nasik,1615).                    travel_dist(nasik,ranchi,1615).
travel_dist(ranchi,panjim,1630).                   travel_dist(panjim,ranchi,1630).
travel_dist(ranchi,patna,302).                     travel_dist(patna,ranchi,302).
travel_dist(ranchi,pondicherry,1935).              travel_dist(pondicherry,ranchi,1935).
travel_dist(ranchi,pune,1675).                     travel_dist(pune,ranchi,1675).
travel_dist(shillong,ahmedabad,2839).              travel_dist(ahmedabad,shillong,2839).
travel_dist(shillong,bangalore,3242).              travel_dist(bangalore,shillong,3242).
travel_dist(shillong,bhubaneshwar,1640).           travel_dist(bhubaneshwar,shillong,1640).
travel_dist(shillong,bombay,3011).                 travel_dist(bombay,shillong,3011).
travel_dist(shillong,calcutta,1281).               travel_dist(calcutta,shillong,1281).
travel_dist(shillong,chandigarh,2416).             travel_dist(chandigarh,shillong,2416).
travel_dist(shillong,cochin,3599).                 travel_dist(cochin,shillong,3599).
travel_dist(shillong,delhi,2126).                  travel_dist(delhi,shillong,2126).
travel_dist(shillong,hyderabad,1309).              travel_dist(hyderabad,shillong,1309).
travel_dist(shillong,indore,2309).                 travel_dist(indore,shillong,2309).
travel_dist(shillong,jaipur,2229).                 travel_dist(jaipur,shillong,2229).
travel_dist(shillong,kanpur,1699).                 travel_dist(kanpur,shillong,1699).
travel_dist(shillong,lucknow,1670).                travel_dist(lucknow,shillong,1670).
travel_dist(shillong,madras,2911).                 travel_dist(madras,shillong,2911).
travel_dist(shillong,nagpur,2114).                 travel_dist(nagpur,shillong,2114).
travel_dist(shillong,nasik,2800).                  travel_dist(nasik,shillong,2800).
travel_dist(shillong,panjim,2925).                 travel_dist(panjim,shillong,2925).
travel_dist(shillong,patna,1019).                  travel_dist(patna,shillong,1019).
travel_dist(shillong,pondicherry,3079).            travel_dist(pondicherry,shillong,3079).
travel_dist(shillong,pune,2860).                   travel_dist(pune,shillong,2860).
travel_dist(shimla,ahmedabad,1256).                travel_dist(ahmedabad,shimla,1256).
travel_dist(shimla,bangalore,2395).                travel_dist(bangalore,shimla,2395).
travel_dist(shimla,bhubaneshwar,2127).             travel_dist(bhubaneshwar,shimla,2127).
travel_dist(shimla,bombay,1753).                   travel_dist(bombay,shimla,1753).
travel_dist(shimla,calcutta,1839).                 travel_dist(calcutta,shimla,1839).
travel_dist(shimla,chandigarh,99).                 travel_dist(chandigarh,shimla,99).
travel_dist(shimla,cochin,3056).                   travel_dist(cochin,shimla,3056).
travel_dist(shimla,delhi,365).                     travel_dist(delhi,shimla,365).
travel_dist(shimla,hyderabad,1812).                travel_dist(hyderabad,shimla,1812).
travel_dist(shimla,indore,1171).                   travel_dist(indore,shimla,1171).
travel_dist(shimla,jaipur,636).                    travel_dist(jaipur,shimla,636).
travel_dist(shimla,kanpur,846).                    travel_dist(kanpur,shimla,846).
travel_dist(shimla,lucknow,659).                   travel_dist(lucknow,shimla,659).
travel_dist(shimla,madras,2588).                   travel_dist(madras,shimla,2588).
travel_dist(shimla,nagpur,1336).                   travel_dist(nagpur,shimla,1336).
travel_dist(shimla,nasik,1567).                    travel_dist(nasik,shimla,1567).
travel_dist(shimla,panjim,2130).                   travel_dist(panjim,shimla,2130).
travel_dist(shimla,patna,1434).                    travel_dist(patna,shimla,1434).
travel_dist(shimla,pondicherry,2759).              travel_dist(pondicherry,shimla,2759).
travel_dist(shimla,pune,1782).                     travel_dist(pune,shimla,1782).
travel_dist(surat,ahmedabad,263).                  travel_dist(ahmedabad,surat,263).
travel_dist(surat,bangalore,1264).                 travel_dist(bangalore,surat,1264).
travel_dist(surat,bhubaneshwar,1579).              travel_dist(bhubaneshwar,surat,1579).
travel_dist(surat,bombay,301).                     travel_dist(bombay,surat,301).
travel_dist(surat,calcutta,1912).                  travel_dist(calcutta,surat,1912).
travel_dist(surat,chandigarh,1325).                travel_dist(chandigarh,surat,1325).
travel_dist(surat,cochin,1593).                    travel_dist(cochin,surat,1593).
travel_dist(surat,delhi,1182).                     travel_dist(delhi,surat,1182).
travel_dist(surat,hyderabad,983).                  travel_dist(hyderabad,surat,983).
travel_dist(surat,indore,607).                     travel_dist(indore,surat,607).
travel_dist(surat,jaipur,932).                     travel_dist(jaipur,surat,932).
travel_dist(surat,kanpur,1296).                    travel_dist(kanpur,surat,1296).
travel_dist(surat,lucknow,1375).                   travel_dist(lucknow,surat,1375).
travel_dist(surat,madras,1695).                    travel_dist(madras,surat,1695).
travel_dist(surat,nagpur,749).                     travel_dist(nagpur,surat,749).
travel_dist(surat,nasik,262).                      travel_dist(nasik,surat,262).
travel_dist(surat,panjim,913).                     travel_dist(panjim,surat,913).
travel_dist(surat,patna,1742).                     travel_dist(patna,surat,1742).
travel_dist(surat,pondicherry,1789).               travel_dist(pondicherry,surat,1789).
travel_dist(surat,pune,412).                       travel_dist(pune,surat,412).
travel_dist(trivandrum,ahmedabad,2197).            travel_dist(ahmedabad,trivandrum,2197).
travel_dist(trivandrum,bangalore,696).             travel_dist(bangalore,trivandrum,696).
travel_dist(trivandrum,bhubaneshwar,1953).         travel_dist(bhubaneshwar,trivandrum,1953).
travel_dist(trivandrum,bombay,1376).               travel_dist(bombay,trivandrum,1376).
travel_dist(trivandrum,calcutta,2376).             travel_dist(calcutta,trivandrum,2376).
travel_dist(trivandrum,chandigarh,3051).           travel_dist(chandigarh,trivandrum,3051).
travel_dist(trivandrum,cochin,218).                travel_dist(cochin,trivandrum,218).
travel_dist(trivandrum,delhi,1950).                travel_dist(delhi,trivandrum,1950).
travel_dist(trivandrum,hyderabad,1261).            travel_dist(hyderabad,trivandrum,1261).
travel_dist(trivandrum,indore,2156).               travel_dist(indore,trivandrum,2156).
travel_dist(trivandrum,jaipur,2782).               travel_dist(jaipur,trivandrum,2782).
travel_dist(trivandrum,kanpur,2611).               travel_dist(kanpur,trivandrum,2611).
travel_dist(trivandrum,lucknow,2690).              travel_dist(lucknow,trivandrum,2690).
travel_dist(trivandrum,madras,748).                travel_dist(madras,trivandrum,748).
travel_dist(trivandrum,nagpur,1834).               travel_dist(nagpur,trivandrum,1834).
travel_dist(trivandrum,nasik,1742).                travel_dist(nasik,trivandrum,1742).
travel_dist(trivandrum,panjim,792).                travel_dist(panjim,trivandrum,792).
travel_dist(trivandrum,patna,2827).                travel_dist(patna,trivandrum,2827).
travel_dist(trivandrum,pondicherry,622).           travel_dist(pondicherry,trivandrum,622).
travel_dist(trivandrum,pune,1533).                 travel_dist(pune,trivandrum,1533).
travel_dist(varanasi,ahmedabad,1373).              travel_dist(ahmedabad,varanasi,1373).
travel_dist(varanasi,bangalore,1791).              travel_dist(bangalore,varanasi,1791).
travel_dist(varanasi,bhubaneshwar,968).            travel_dist(bhubaneshwar,varanasi,968).
travel_dist(varanasi,bombay,1597).                 travel_dist(bombay,varanasi,1597).
travel_dist(varanasi,calcutta,695).                travel_dist(calcutta,varanasi,695).
travel_dist(varanasi,chandigarh,1032).             travel_dist(chandigarh,varanasi,1032).
travel_dist(varanasi,cochin,2331).                 travel_dist(cochin,varanasi,2331).
travel_dist(varanasi,delhi,745).                   travel_dist(delhi,varanasi,745).
travel_dist(varanasi,hyderabad,1189).              travel_dist(hyderabad,varanasi,1189).
travel_dist(varanasi,indore,925).                  travel_dist(indore,varanasi,925).
travel_dist(varanasi,jaipur,835).                  travel_dist(jaipur,varanasi,835).
travel_dist(varanasi,kanpur,315).                  travel_dist(kanpur,varanasi,315).
travel_dist(varanasi,lucknow,286).                 travel_dist(lucknow,varanasi,286).
travel_dist(varanasi,madras,1985).                 travel_dist(madras,varanasi,1985).
travel_dist(varanasi,nagpur,713).                  travel_dist(nagpur,varanasi,713).
travel_dist(varanasi,nasik,1399).                  travel_dist(nasik,varanasi,1399).
travel_dist(varanasi,panjim,1524).                 travel_dist(panjim,varanasi,1524).
travel_dist(varanasi,patna,280).                   travel_dist(patna,varanasi,280).
travel_dist(varanasi,pondicherry,2153).            travel_dist(pondicherry,varanasi,2153).
travel_dist(varanasi,pune,1459).                   travel_dist(pune,varanasi,1459).
travel_dist(vijayawada,ahmedabad,1705).            travel_dist(ahmedabad,vijayawada,1705).
travel_dist(vijayawada,bangalore,637).             travel_dist(bangalore,vijayawada,637).
travel_dist(vijayawada,bhubaneshwar,775).          travel_dist(bhubaneshwar,vijayawada,775).
travel_dist(vijayawada,bombay,973).                travel_dist(bombay,vijayawada,973).
travel_dist(vijayawada,calcutta,1198).             travel_dist(calcutta,vijayawada,1198).
travel_dist(vijayawada,chandigarh,1959).           travel_dist(chandigarh,vijayawada,1959).
travel_dist(vijayawada,cochin,1174).               travel_dist(cochin,vijayawada,1174).
travel_dist(vijayawada,delhi,1716).                travel_dist(delhi,vijayawada,1716).
travel_dist(vijayawada,hyderabad,269).             travel_dist(hyderabad,vijayawada,269).
travel_dist(vijayawada,indore,1255).               travel_dist(indore,vijayawada,1255).
travel_dist(vijayawada,jaipur,1660).               travel_dist(jaipur,vijayawada,1660).
travel_dist(vijayawada,kanpur,1519).               travel_dist(kanpur,vijayawada,1519).
travel_dist(vijayawada,lucknow,1598).              travel_dist(lucknow,vijayawada,1598).
travel_dist(vijayawada,madras,432).                travel_dist(madras,vijayawada,432).
travel_dist(vijayawada,nagpur,742).                travel_dist(nagpur,vijayawada,742).
travel_dist(vijayawada,nasik,1428).                travel_dist(nasik,vijayawada,1428).
travel_dist(vijayawada,panjim,876).                travel_dist(panjim,vijayawada,876).
travel_dist(vijayawada,patna,1664).                travel_dist(patna,vijayawada,1664).
travel_dist(vijayawada,pondicherry,598).           travel_dist(pondicherry,vijayawada,598).
travel_dist(vijayawada,pune,842).                  travel_dist(pune,vijayawada,842).
travel_dist(vishakapatnam,ahmedabad,1815).         travel_dist(ahmedabad,vishakapatnam,1815).
travel_dist(vishakapatnam,bangalore,1093).         travel_dist(bangalore,vishakapatnam,1093).
travel_dist(vishakapatnam,bhubaneshwar,445).       travel_dist(bhubaneshwar,vishakapatnam,445).
travel_dist(vishakapatnam,bombay,1754).            travel_dist(bombay,vishakapatnam,1754).
travel_dist(vishakapatnam,calcutta,868).           travel_dist(calcutta,vishakapatnam,868).
travel_dist(vishakapatnam,chandigarh,2127).        travel_dist(chandigarh,vishakapatnam,2127).
travel_dist(vishakapatnam,cochin,1449).            travel_dist(cochin,vishakapatnam,1449).
travel_dist(vishakapatnam,delhi,1881).             travel_dist(delhi,vishakapatnam,1881).
travel_dist(vishakapatnam,hyderabad,599).          travel_dist(hyderabad,vishakapatnam,599).
travel_dist(vishakapatnam,indore,1433).            travel_dist(indore,vishakapatnam,1433).
travel_dist(vishakapatnam,jaipur,1838).            travel_dist(jaipur,vishakapatnam,1838).
travel_dist(vishakapatnam,kanpur,1687).            travel_dist(kanpur,vishakapatnam,1687).
travel_dist(vishakapatnam,lucknow,1765).           travel_dist(lucknow,vishakapatnam,1765).
travel_dist(vishakapatnam,madras,762).             travel_dist(madras,vishakapatnam,762).
travel_dist(vishakapatnam,nagpur,910).             travel_dist(nagpur,vishakapatnam,910).
travel_dist(vishakapatnam,nasik,1596).             travel_dist(nasik,vishakapatnam,1596).
travel_dist(vishakapatnam,panjim,1206).            travel_dist(panjim,vishakapatnam,1206).
travel_dist(vishakapatnam,patna,1334).             travel_dist(patna,vishakapatnam,1334).
travel_dist(vishakapatnam,pondicherry,930).        travel_dist(pondicherry,vishakapatnam,930).
travel_dist(vishakapatnam,pune,1658).              travel_dist(pune,vishakapatnam,1658).

go :-   write("Which algorithm you want to choose? Depth-First (1) OR Best-First (2) :- "),
        read(X),
        write("Enter the current city :- "), 
        read(City),
        write("Enter the city you want to go to :- "), 
        read(Destination),
        check(X, City, Destination, Route),
        rev(Route, [], Final),
        write("The route that you should take is :- "),
        write(Final).

rev([], Result, Result).
rev([H|T], X, Result) :- rev(T, [H|X], Result).

check(1, City, Destination, Route) :- depth_first_search([[City]], Destination, Route).
check(2, City, Destination, Route) :- best_first_search([[City]], Destination, Route).

%------------------------------------------------------------------------------------------------------------------------------------------------------------------------

depth_first_search([[Destination|Route]|_], Destination, [Destination|Route]).

depth_first_search([Route|Queue], Destination, FinalRoute):-  possible_routes(Route, NewRoute), append(NewRoute, Path, NewPath), depth_first_search(NewPath, Destination, FinalRoute).

visited(City, [City|_]).
visited(City, [_|Route]) :- visited(City, Route).

possible_routes([City|Route],NewRoute) :- findall([NextCity,City|Route], (travel_dist(City,NextCity,_), not(visited(NextCity,Route))), NewRoute).

%------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/*underdetermined values of the distances. */

heuristic(agartala, agra, 2500).                        heuristic(agra, allahabad, 2500).
heuristic(agartala, allahabad, 2000).                   heuristic(allahabad, agartala, 2000).
heuristic(agartala, amritsar, 3000).                    heuristic(amritsar, agartala, 3000).
heuristic(agartala, asansol, 2000).                     heuristic(asansol, agartala, 2000).
heuristic(agartala, baroda, 3200).                      heuristic(baroda, agartala, 3200).
heuristic(agartala, bhopal, 2800).                      heuristic(bhopal, agartala, 2800).
heuristic(agartala, calicut, 4100).                     heuristic(calicut, agartala, 4100).
heuristic(agartala, coimbatore, 3900).                  heuristic(coimbatore, agartala, 3900).
heuristic(agartala, gwalior, 2500).                     heuristic(gwalior, agartala, 2500).
heuristic(agartala, hubli, 3700).                       heuristic(hubli, agartala, 3700).
heuristic(agartala, imphal, 3200).                      heuristic(imphal, agartala, 3200).
heuristic(agartala, jabalpur, 2800).                    heuristic(jabalpur, agartala, 2800).

heuristic(X, Y, _) :- heuristic(X, Y, _);
                    travel_dist(X, Y, Dist),
                    assert(heuristic(X, Y, Dist-100));

%:- dynamic heuristic/3

best_first_search([[Destination|Route]|_], Destination, [Destination|Route]).

best_first_search([Route|Queue], Destination, FinalRoute):-  possible_routes(Route, NewRoute), append(NewRoute, Path, NewPath), best_first_search(NewPath, Destination, FinalRoute).

visited(City, [City|_]).
visited(City, [_|Route]) :- visited(City, Route).

possible_routes([City|Route],NewRoute) :- findall([NextCity,City|Route], (travel_dist(City,NextCity,_), not(visited(NextCity,Route))), NewRoute).

/* wasnt able to understand queue part and didn't impliment it. */